### ISSUE TITLE
Screen appropriate links

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVEWasp#10]
The hive bot currently pulls links over from the chat channel.
A safety enhancement may be to compare the base URL against a list of 'bad' sites and if the link is not appropriate, it not be pulled over, and perhaps drops a message in the chat that this link from 'someone' was not appropriate.  This will not help with re-directs (bit.ly), but it may add a degree of safety for the channel.

**Comment by Blade2021** [comment]
While I fully support the idea.  This would be very controversial as the doc covers many subjects so narrowing it down to a whitelist or blacklist would be very cumbersome.  Gonna have to pass for now.
