### ISSUE TITLE
Add Stream Start Notification to #live-stream-links

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVEWasp#11]
To make streams identifiable in the Links channel, I propose a Hive enhancement to add a message to links at the start of every stream.  
You could possibly use the notify 'signal' internally to also message live-stream-links 'stream has started' as part of that action.  
Not a double trigger, just another action off the same logic that fires ~notify trigger.
If this is not feesable, any other appropriate method would also work.

**Comment by Blade2021** [comment]
Done.
