### ISSUE TITLE
Swear filter

### ISSUE THREAD

**Issue by Timp103** [Blade2021/HIVEWasp#14]
whenever someone use a blacklisted word hive could just ask them to use nicer language. I know it can not edit what was said but perhaps it can remove it. blacklisted words would be stuff like the f-bomb, C-word, N-word, non medical slang for body parts things like that.

**Comment by Blade2021** [comment]
I've been considering doing a mod bot for stuff like that.   I'll see what I can do.

**Comment by Blade2021** [comment]
Implemented.
