### ISSUE TITLE
Spamming enable during stream.

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVEWasp#5]
Add a feature to, at random intervals, drop random reminders in the chat. 
IE:    Replace the mods dropping tn the !prime, !sub, !az, etc. type messages.   
A set of messages would be provided, it would random pick at random times within an adjustable range when to drop them.

**Comment by ikifar2012** [comment]
Can’t Nightbot already do this with the “timers” feature?

**Comment by Blade2021** [comment]
Sorry @SirGoodenough as Matheson stated, these are already features in NightBot currently.
